language: python
python:
  - "2.7"
  - "3.6"
  # PyPy versions
  - "pypy2.7"
  - "pypy3.6"
# command to install dependencies
install:
  - python setup.py install
  - pip install pytest-runner pytest pytest-cov
# command to run tests
script: python setup.py test
