language: python
python:
- '3.6'
- '3.7'
- '3.8'
install:
- python setup.py install
- pip install pytest-runner pytest pytest-cov python-coveralls
script:
- python setup.py test
after_success:
- coveralls

deploy:
  python: '3.7'
  provider: pypi
  user: __token__
  distributions: 'sdist bdist_wheel'
  skip_existing: true
  cleanup: true
  password:
    secure: Eh+KtTMmTzm/L4xIRg5TqpvWofZ2xXO4zNe4VSMgBE+zL1KnoZ2NuDwlEChSZPmA1NJGq7DhAx43la9FCfx7UotsPtq1MmrgnnkUiMgmY+3d5thKFlvjkooh9b4m/edkaOqbEeLCxOIftRbs8lkWsB/nE85DCX7p0hmxST8Qx88hQmODPD0L4eLUs388KrMOFxGNLyrJcR2ebTtQ/W+c9MIYpj6TKSDB8Iv6lVDiko6Wur2+fo7wKffo72VOETOaVJPw0B2IWz3fZ4gIDsoDe3AJvE54Y3VZOHsuovGX3AaQcAwaRAjAHV8evu4YmDnMgA9RfqLRtPH4yv1sRbkQSP2O2neUNlmOrhzFk+xm/mMsFUzZDpxBac7MLSJ3V3kmmJmDgmeaxi8Hkp576YGKUtC/OmUM0a5M5nuTS8f6fCQLjffKKXP8YRbmt0Na48HGYD33xA2C8TqJmZow00d1EwSCF9Zk9m+age+MZ1vGulXZP1wYoz7zdy4uh2yKwTZPEZYuTgdVk/dquK8jtND6BdqDXCqz6ElBqQZ3J4YEoA2O/Vz2OhK+t18WdTL4ixTEv45vfvHwjK0JRCBP0Zqqc/4i6soa/u2t0wJsrC+T/F1dYHmwOlSalRKrI+rbdHk6Ou57S8XPIIOFdsf7q5ik+1qoQn4CXxsB0JoEq1fx3do=
